# Add these lines to your YAML file
slam_toolbox:
  ros__parameters:
    # ... other parameters ...
    track_unknown_space: true
    free_thresh: 0.196
    transform_publish_period: 0.02
    map_update_interval: 1.0
    resolution: 0.05
    max_laser_range: 15.0
    stagefetch_laser_service: 'stagefetch_laser_service'
    clear_buffer_service: 'clear_buffer_service'
    # Adjust these parameters for your robot's specific dimensions
    robot_base_frame: 'base_link'
    robot_radius: 0.3  # Adjust based on your robot's size
    footprint_clearing_enabled: true
    clearing_rotation_allowed: true
    update_footprint_enabled: true
    lethal_cost_threshold: 100